SET CLOUDWORK=%~dp0../../../../..
SET ERSCRIPTV1=%CLOUDWORK%/Scripting/ERScript_r4

SET SAXON_PATH=%ERSCRIPTV1%/thirdparty/SaxonHE9-7-0-19J
SET JING_PATH=%ERSCRIPTV1%//thirdparty/jing-20091111/bin


SET ERSCRIPTV2=%~dp0../../..
SET XXDIAGRAM_SCHEMAS=%ERSCRIPTV2%/diagramModelasERv1.2/bin

SET DIAGRAM_GENERATORS=%ERSCRIPTV2%/ERmodel_v2.1/xslt